name: deploy-main-branch
on:
  push:
    workflow_dispatch:
    branches:
      - main
      - 'i1/*'
jobs:
  deploy-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3