name: deploy-main-branch
on:
  push:
    workflow_dispatch:
    branches:
      - main
      - 'i1/*'
jobs:
  deploy-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Project
        uses: actions/setup-project@v1